name: LightTest

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        name: checkout repo
      - name: cache
        uses: actions/cache@v1.1.2
        id: cache-test
        env:
          cache-name: cached-test
        with:
          path: /var/tmp/ff
          key: build-${{ env.cache-name }}
      - name: checkout submodules
        if: steps.cache-test.outputs.cache-hit != 'true'
        shell: bash
        run: |
          cd /var/tmp && mkdir -p ff
          cd ff && touch test.txt
          echo "Lorem ipsum" > test.txt
      - name: cache success
        if: steps.cache-test.outputs.cache-hit == 'true'
        shell: bash
        run: |
            cd /var/tmp/ff && cat test.txt
